api-version: 2021-10-01
location: westus
name: streamlit_azure-2
properties:
  containers:
  - name: streamlitapp
    properties:
      image: bpdsregistry.azurecr.io/azure_demo:v2
      ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
      resources:
        requests:
          cpu: 2.0
          memoryInGB: 1.5
      volumeMounts:
      - mountPath: /aci/data/
        name: filesharevolume
  imageRegistryCredentials:
  - server: bpdsregistry.azurecr.io
    username: bpdsregistry
    password: 6k1xs6BWKM0BL9PMFTcLvh/DCW77uj6F
  restartPolicy: Never
  ipAddress:
    ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
    type: Public
    dnsNameLabel: streamlit-azure-2
  osType: Linux
  volumes:
  - name: filesharevolume
    azureFile:
      sharename: streamlit-azure-fileshare
      storageAccountName: bpdsstreamlit
      storageAccountKey: 7mm9gyINS2sXTJWzu8Kn8ZXcXD8dZPW1grMhQ++XspgJtcim+DQnCstqreXMbkLji9ZZMBtpdHGd+AStkadttA==
tags: {}
type: Microsoft.ContainerInstance/containerGroups
